---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance1
    image_owner: "099720109477"
    image_name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
    instance_type: t3.medium
    vpc_subnet_id: subnet-26c2de6b
    security_groups: [ "sg-39e96c21" ]
    tags:
      Name: molecule_instance1
    groups:
      - db
  - name: instance2
    image_owner: "099720109477"
    image_name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
    instance_type: t3.medium
    vpc_subnet_id: subnet-26c2de6b
    security_groups: [ "sg-39e96c21" ]
    tags:
      Name: molecule_instance2
    groups:
      - db
  - name: instance3
    image_owner: "099720109477"
    image_name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
    instance_type: t3.medium
    vpc_subnet_id: subnet-26c2de6b
    security_groups: [ "sg-39e96c21" ]
    tags:
      Name: molecule_instance3
    groups:
      - db
provisioner:
  name: ansible
verifier:
  name: ansible
