xtradb_cluster_name: "morpheus"
xtradb_root_password: 'evenmores3cr3t'
xtradb_db_user: 'morpheus'
xtradb_db_pass: 's3cr3t'

xtradb_nodes_group: "db"
xtradb_database_name: "morpheusdb"

xtradb_databases:
    - name: "{{ xtradb_database_name }}"
xtradb_users:
    - name: "{{ xtradb_db_user }}"
      host: '%'
      password: "{{ xtradb_db_pass }}"
      priv: "*.*:SELECT,PROCESS,SHOW DATABASES/{{xtradb_database_name}}.*:ALL"
      append_privs: false